language: node_js
node_js:
  - 12

  env:
  - DATABASE_URL=postgresql://postgresql://codex:pg123@localhost:5432/greeting

  before_script:
  - psql -c 'create database  greeting;' -U postgres
  - psql -U postgres -d greeting -a -f tables.sql

services:
  - postgresql