
language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/greeting;

node_js:  
  - "12"

before_script:
  - psql -c 'create database greeting;' -U postgres
  - psql -U postgres -d greeting -a -f table.sql


services:
  - postgresql;
