
language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/greeting_test

node_js:  
  - 12

before_script:
  - psql -c 'create database greeting_test;' -U postgres

services:
  - postgresql