
language: node_js
env:
  - DATABASE_URL = 'postgresql://codex:pg123@localhost:5432/greeting'
node_js:
  - 12
before_script:
  - psql -c 'create database  greeting;' -U postgres
  - psql -U postgres -d greeting -a -f tables.sql

services:
  - postgresql
